//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanstvo
    {
        public int IDClan { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Telefon { get; set; }
        public string BrLicne { get; set; }
        public string Paket { get; set; }
        public string ClanInfo { get; set; }
    }
}
