//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int IDFilm { get; set; }
        public string Ime { get; set; }
        public string Vreme { get; set; }
        public string Datum { get; set; }
        public string Opis { get; set; }
        public string Cena { get; set; }
    }
}
