//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopProjekat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BioskopEnti2 : DbContext
    {
        public BioskopEnti2()
            : base("name=BioskopEnti2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bioskop> Bioskops { get; set; }
        public virtual DbSet<Clanstvo> Clanstvoes { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<StavkaRacuna> StavkaRacunas { get; set; }
    }
}
