//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaRacuna
    {
        public int IDRacuna { get; set; }
        public int RedniBroj { get; set; }
        public string ImeFilma { get; set; }
        public string BrKarata { get; set; }
        public string MestaSed { get; set; }
        public string Vreme { get; set; }
        public string Datum { get; set; }
        public string CenaKarte { get; set; }
    
        public virtual Racun Racun { get; set; }
    }
}
